allowlist:
  - number: "+919921919072"
    name: "Girija"
  - number: "+919594942173"
    name: "Ssonal"
  - number: "+12012539823"
    name: "Sasmit"
  - number: "+919373326480"
    name: "Anita"
  - number: "+919552550062"
    name: "Sachin"
  - number: "+919552550061"
    name: "Sarika"
  - number: "+919422517129"
    name: "Preetee"
  - number: "+919945222604"
    name: "Deepa"
  - number: "+919886313317"
    name: "Sowmya"
  - number: "+919011050776"
    name: "Samarjeet"
  - number: "+918446482842"
    name: "Mrunmayee"
  - number: "+918956651359"
    name: "Saee"
  - number: "+917057317639"
    name: "Shrushty"
  - number: "+917350854727"
    name: "Dev"
  - number: "+917588722191"
    name: "Kabir"
  - number: "+917977867400"
    name: "Hemant"
  - number: "+919330771589"
    name: "Vaani"
  - number: "+919920314603"
    name: "Arun"
  - number: "+919833669811"
    name: "Amey"
admins:
  - number: "+919130099484"
    name: "Santosh"
  - number: "+919130017237"
    name: "Shilpa"
messages:
  waitlist: "Thanks for reaching out! meCove is currently in closed beta. We'll be in touch when your access opens up."
